mqinstance:
  name: telco-cloud
  namespace: gitops-cp-queue-manager
  spec:
    license:
      accept: true
      license: L-RJON-C7QG3S
      use: NonProduction
    queueManager:
      name: QM1
    version: 9.2.4.0-r1
    web:
      enabled: true