mqinstance:
  name: quickstart-cp4i
  namespace: cp4i-dev
  spec:
    license:
      accept: true
      license: L-RJON-C7QG3S
      use: NonProduction
    queueManager:
      name: QM1
    version: 9.2.4.0-r1
    web:
      enabled: true